### ISSUE TITLE
Issue No. 10: High BLER observed in UL during UE attach

### ISSUE THREAD

**Issue by ashwanikumar05** [Telecominfraproject/vRAN-Airtel#7]
Issue Summary: High BLER observed in UL during UE attach
Reported date: Sep, 18, 2019, Status: Open

Remarks: Reduction in BLER observed in L2 Logs after reducing Interference, L1 logs have been shared for analysis.

**Comment by PushkarRaj-GH** [comment]
Reduction in BLER observed in L2 Logs after reducing the Interference. Earlier the BLER was around 50% now the BLER is around 4%. L1 logs have been re-verified by Phluido.
Its discussed that this is with permissible limit hence closing this issue.

**Comment by PushkarRaj-GH** [comment]
Steps:
---------
1. Altran has changed the EARFCN for the emitting eNodeB.
2. Altran has again executed the test case.
3. This time we have observed BLER in the range of 2 to 4 %. Earlier it was more than 50%.
