### ISSUE TITLE
Issue No. 12: Attach is getting rejected on multiple occasions from EPC with reason “Illegal UE” during 1 Hour 32 UE attach-detach run 

### ISSUE THREAD

**Issue by ashwanikumar05** [Telecominfraproject/vRAN-Airtel#9]
Issue Summary: Attach is getting rejected on multiple occasions from EPC with reason “Illegal UE” during 1 Hour 32 UE attach-detach run 

Reported date: Sep, 30, 2019, Status: Open; Phase 2 issue

Remarks: Altran team is analysing on this issue

**Comment by PushkarRaj-GH** [comment]
We are closing this issue.

Steps:
--------
1. Altran has upgraded Altran EPC to the latest version.
2. Altran has repeated this test case.
3. This time Altran didn't observe multiple Attach rejects.
